### ISSUE TITLE
issue: OS puller

### ISSUE THREAD

**Issue by aadams** [Uniswap/v3-polars#3]
there is no open source puller. i would like people to be able to re-produce my work using it, but i have little experience with good OS data. its also annoying for others to work for so pls help me

all the data required is events, so I just need help w/ an arbitrary publicly reproducible OS event puller (in exchange for any professors using it to cite this pls 👀 )

**Comment by derekbar90** [comment]
@aadams I've messaged you on a few platforms but I have been working on something similar and would love to discuss data options and data-intensive pipelines like event sourcing and ways I've overcome it. Twitter: @derekbarrera

**Comment by aadams** [comment]
this is done now with allium!
